### ISSUE TITLE
please provide a source tarball including external dependencies

### ISSUE THREAD

**Issue by sandrotosi** [rapidfuzz/Levenshtein#59]
Hello,
i maintain Levenshtein in Debian and while working to package 0.24.0, i noticed that you're using the `extern` directory with a git submodule to another project. that setup is also replicated in the source tarball release via github when you tag a release (the PyPI tarballs for 0.23.0, since 0.24.0 is currently not uploaded to that system, seems to be empty so i'm basing my work on github tarballs).

This creates an issue in Debian, since we cannot download anything from internet while building a package, so im asking if you could release a new artifact that includes the source code both for Levenshtein and any external dependency (they can live in extern, is that's where the build system expects them to be).

thanks for considering!

**Comment by maxbachmann** [comment]
> he PyPI tarballs for 0.23.0, since 0.24.0 is currently not uploaded to that system, seems to be empty so i'm basing my work on github tarballs

I assume you mean the sdist on pypi. That one should contain the files. I assume you are still using the old https://pypi.org/project/python-Levenshtein/ which is basically just an installer for this project. You would have to use https://pypi.org/project/Levenshtein/0.24.0/#files instead.

> so im asking if you could release a new artifact that includes the source code both for Levenshtein and any external dependency (they can live in extern, is that's where the build system expects them to be).

Not sure how to do this automatically of the top of my head, but if the other options are really not enough I would look into it.


The library is already packaged for multiple systems. Usually it's based either on:
- sdist on pypi
- github with everything packaged separately. E.g. fedora has the following packages:
  - rapidfuzz-cpp
  - taskflow
  - python3-rapidfuzz
  - python-Levenshtein

**Comment by maxbachmann** [comment]
You would need to package at least rapidfuzz for debian as well. I know someone wanted to do this in the past, but back then Cython 3 was not available for debian which was an issue. I assume it should probably be available now though.

**Comment by maxbachmann** [comment]
ping @sandrotosi whats the state of this and is there anything I can helps with? I have been contacted by others relying on the package in Debian about it being dropped soon because the current version doesn't work on Python3.12

@juliangilbey adding you here as well, since you started working on bringing rapidfuzz to debian, which is a pre-requirement here as well.

Let me know if there is anything I can do to help.

**Comment by maxbachmann** [comment]
I think now that rapidfuzz and taskflow are packaged separately for debian this is no longer an issue.
