### ISSUE TITLE
jaro_winkler gives values larger than 1. 

### ISSUE THREAD

**Issue by YagmurGULEC** [rapidfuzz/Levenshtein#63]
Hello,

Thanks for the implementation of this library. It is very useful. I was trying to use it to find the root of a word based on similarity. However I came across with some values bigger than 1 with this setting. 
jaro_winkler('milyarder', 'milyarderlik',prefix_weight=0.5)
1.0833
jaro_winkler('milyarderlik','milyarder',prefix_weight=1)
1.25 
In the documentation (https://rapidfuzz.github.io/Levenshtein/levenshtein.html#jaro-winkler), it is written that the jaro_winkler should be between 0 and 1. I was wondering if I put a invalid prefix weight. In this case, I assumed it should have raised a valueError as mentioned in the documentation.
Thanks in advance.

**Comment by maxbachmann** [comment]
That is certainly a bug. It should make sure the score can never be larger than 1.0.

**Comment by maxbachmann** [comment]
This is fixed in the latest release
