### ISSUE TITLE
Op out of bounds

### ISSUE THREAD

**Issue by allComputableThings** [rapidfuzz/Levenshtein#66]
```
Levenshtein.editops('candel', 'candle')
-> [('insert', 4, 4), ('delete', 5, 6)]
```
I'm a little confused about the result.
```
('insert', 4, 4)    # li=4, ri=4
```
....I take to mean insert  `'candle'[ri]`  at `li` in `'candel'`. Which gives us: `'candlel'`
And `('delete', 5, 6)`:   delete position 5 of this new string `'candlel'`.

Where does the 6 come from? Shouldn't it be null?

"candle"[6] seems out of bounds.

Also, I assume from this that these indexes `si,di`  of `(ops, si, di)` are values in the 'working/current' string under transformation, right?

- It's not safe to use `si` always as an index in the first string (insert and delete shift characters in it).
- `si` *should* always be an index into the second/target/destination string though, right?

**Comment by maxbachmann** [comment]
The structure is `(tag, src_pos, dest_pos)`. As you noted the `dest_pos` for deletions doesn't make any sense, since there is no reference to the destination strings for. So it would be cleaner to set this to `None` at some instead to make this clearer.

> Also, I assume from this that these indexes si,di of (ops, si, di) are values in the 'working/current' string under transformation, right?

No they always refer to the two strings passed into the `editops` call. You could transform the source into the destination string in the following way:
```python
source_string, destination_string = 'candel', 'candle'
ops = Levenshtein.editops(source_string, destination_string)

res_str = ""
src_pos = 0
for op in ops:
    # matches between last and current editop
    while src_pos < op[1]:
        res_str += source_string[src_pos]
        src_pos += 1

    if op[0] == "replace":
        res_str += destination_string[op[2]]
        src_pos += 1
    elif op[0] == "insert":
        res_str += destination_string[op[2]]
    elif op[0] == "delete":
        src_pos += 1

# matches after the last editop
while src_pos < len(source_string):
    res_str += source_string[src_pos]
    src_pos += 1

print(res_str)
```
